version: '3.8'
services:
  motoapp:
    image: postgres:15
    container_name: motoapp
    environment:
      POSTGRES_DB: motoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"