version: '3.8'

services:
  app:
    build: .
    container_name: motorcycle_app
    ports:
      - "8080:8080"
    depends_on:
      - motoapp
    environment:
      SERVER_ADDRESS: "0.0.0.0:8080"
      DB_HOST: motoapp
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: motoapp
      JWT_SECRET: secret
    networks:
      - backend

  motoapp:
    image: postgres:15
    container_name: motoapp
    environment:
      POSTGRES_DB: motoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - backend

networks:
  backend: